import { NextResponse } from "next/server";
import { Resend } from "resend";

export async function POST(req: Request) {
    try {
        const body = await req.json();
        const { type, data } = body;

        // 1. Verify API Key exists before initializing
        const apiKey = process.env.RESEND_API_KEY;
        if (!apiKey) {
            console.error("Resend Configuration Error: RESEND_API_KEY is completely missing from .env.local");
            return NextResponse.json(
                { success: false, message: "Server configuration error: Missing Resend API Key. Please add RESEND_API_KEY to your .env.local file." },
                { status: 500 }
            );
        }

        // 2. Initialize safely inside the try-catch
        const resend = new Resend(apiKey);

        let subject = "";
        let htmlTemplate = "";

        if (type === "contact") {
            const { name, email, subject: userSubject, message } = data;
            
            if (!name || !email || !message) {
                return NextResponse.json({ success: false, message: "Missing required fields." }, { status: 400 });
            }

            subject = `New Contact Request: ${userSubject || 'General Inquiry'} from ${name}`;
            htmlTemplate = `
                <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #eaeaea; border-radius: 10px; overflow: hidden;">
                    <div style="background-color: #2563eb; padding: 20px; text-align: center;">
                        <h2 style="color: white; margin: 0;">New Support Ticket</h2>
                    </div>
                    <div style="padding: 30px; background-color: #fafafa;">
                        <p style="margin-bottom: 5px; color: #666;"><strong>From:</strong> ${name}</p>
                        <p style="margin-top: 0; margin-bottom: 20px; color: #666;"><strong>Email:</strong> <a href="mailto:${email}">${email}</a></p>
                        
                        <div style="background-color: white; padding: 20px; border-radius: 8px; border: 1px solid #eaeaea;">
                            <h3 style="margin-top: 0; color: #333;">Message:</h3>
                            <p style="color: #444; line-height: 1.6; white-space: pre-wrap;">${message}</p>
                        </div>
                    </div>
                    <div style="background-color: #f1f5f9; padding: 15px; text-align: center; color: #94a3b8; font-size: 12px;">
                        This email was automatically generated by the ShopX Contact System.
                    </div>
                </div>
            `;
        } else if (type === "vendor") {
            const { businessName, contactName, email, phone, businessType, address, category, experience } = data;

            if (!businessName || !email || !phone) {
                return NextResponse.json({ success: false, message: "Missing required fields." }, { status: 400 });
            }

            subject = `New Vendor Application: ${businessName}`;
            htmlTemplate = `
                <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #eaeaea; border-radius: 10px; overflow: hidden;">
                    <div style="background-color: #7c3aed; padding: 20px; text-align: center;">
                        <h2 style="color: white; margin: 0;">New Vendor Partnership</h2>
                    </div>
                    <div style="padding: 30px; background-color: #fafafa;">
                        <h3 style="color: #333; margin-top: 0; border-bottom: 2px solid #e2e8f0; padding-bottom: 10px;">Business Details</h3>
                        <table style="width: 100%; border-collapse: collapse; margin-bottom: 25px;">
                            <tr>
                                <td style="padding: 8px 0; color: #64748b; width: 140px;"><strong>Business Name:</strong></td>
                                <td style="padding: 8px 0; color: #0f172a; font-weight: bold;">${businessName}</td>
                            </tr>
                            <tr style="background-color: #f1f5f9;">
                                <td style="padding: 8px 10px; color: #64748b;"><strong>Contact Name:</strong></td>
                                <td style="padding: 8px 10px; color: #0f172a;">${contactName}</td>
                            </tr>
                            <tr>
                                <td style="padding: 8px 0; color: #64748b;"><strong>Email:</strong></td>
                                <td style="padding: 8px 0; color: #0f172a;"><a href="mailto:${email}">${email}</a></td>
                            </tr>
                            <tr style="background-color: #f1f5f9;">
                                <td style="padding: 8px 10px; color: #64748b;"><strong>Phone:</strong></td>
                                <td style="padding: 8px 10px; color: #0f172a;">${phone}</td>
                            </tr>
                            <tr>
                                <td style="padding: 8px 0; color: #64748b;"><strong>Business Type:</strong></td>
                                <td style="padding: 8px 0; color: #0f172a;">${businessType}</td>
                            </tr>
                            <tr style="background-color: #f1f5f9;">
                                <td style="padding: 8px 10px; color: #64748b;"><strong>Core Category:</strong></td>
                                <td style="padding: 8px 10px; color: #0f172a;">${category}</td>
                            </tr>
                            <tr>
                                <td style="padding: 8px 0; color: #64748b;"><strong>Experience:</strong></td>
                                <td style="padding: 8px 0; color: #0f172a;">${experience ? experience + ' years' : 'Not specified'}</td>
                            </tr>
                        </table>

                        <h3 style="color: #333; margin-top: 0; border-bottom: 2px solid #e2e8f0; padding-bottom: 10px;">Address Details</h3>
                        <p style="color: #444; line-height: 1.6; white-space: pre-wrap; background-color: white; padding: 15px; border-radius: 8px; border: 1px solid #eaeaea;">${address || 'Not provided'}</p>
                    </div>
                    <div style="background-color: #f1f5f9; padding: 15px; text-align: center; color: #94a3b8; font-size: 12px;">
                        This application was submitted via the ShopX Vendor Portal.
                    </div>
                </div>
            `;
        } else if (type === "vendor_order") {
            const { orderId, products, totalEarning, vendorName } = data;

            if (!orderId || !vendorName) {
                return NextResponse.json({ success: false, message: "Missing required order fields." }, { status: 400 });
            }

            // Fallback for empty products array
            const productList = products && products.length > 0 ? products : [];

            // Helper to format LKR
            const formatLKR = (amount: any) => {
                const num = parseFloat(amount || "0");
                if (isNaN(num)) return "Rs. 0.00";
                return `Rs. ${num.toLocaleString('en-LK', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
            };

            // Generate Table Rows
            const productsHtml = productList.length > 0 
                ? productList.map((item: any) => {
                    const price = formatLKR(item.price);
                    const total = formatLKR(item.total);
                    const earning = formatLKR(item.earning || (item.total * 0.90)); // Fallback 10% commission calc if undefined
                    
                    return `
                        <tr style="border-bottom: 1px solid #eaeaea;">
                            <td style="padding: 12px; color: #333;">
                                <strong>${item.name || 'Unknown Product'}</strong><br/>
                                <span style="color: #666; font-size: 12px;">Qty: ${item.quantity || 1}</span>
                            </td>
                            <td style="padding: 12px; color: #555;">${price}</td>
                            <td style="padding: 12px; color: #555;">${total}</td>
                            <td style="padding: 12px; color: #16a34a; font-weight: bold;">${earning}</td>
                        </tr>
                    `;
                }).join('')
                : `
                    <tr>
                        <td colspan="4" style="padding: 20px; text-align: center; color: #999; font-style: italic;">
                            No product details found for this order.
                        </td>
                    </tr>
                `;

            subject = `New Order Received! [Order #${orderId}]`;
            htmlTemplate = `
                <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #eaeaea; border-radius: 10px; overflow: hidden;">
                    <div style="background-color: #10b981; padding: 25px; text-align: center;">
                        <h2 style="color: white; margin: 0; font-size: 24px;">New Order Received! 🎉</h2>
                        <p style="color: #d1fae5; margin-top: 5px; margin-bottom: 0;">Order #${orderId}</p>
                    </div>
                    
                    <div style="padding: 30px; background-color: #ffffff;">
                        <p style="color: #333; font-size: 16px;">Hello <strong>${vendorName}</strong>,</p>
                        <p style="color: #555; line-height: 1.5;">Great news! You have received a new order on ShopX. Please review the details below and prepare the items for fulfillment.</p>
                        
                        <h3 style="color: #111; margin-top: 30px; border-bottom: 2px solid #f1f5f9; padding-bottom: 10px;">Order Details</h3>
                        
                        <table style="width: 100%; border-collapse: collapse; text-align: left; margin-bottom: 20px;">
                            <thead>
                                <tr style="background-color: #f8fafc; border-bottom: 2px solid #e2e8f0;">
                                    <th style="padding: 12px; color: #475569; font-size: 14px;">Product</th>
                                    <th style="padding: 12px; color: #475569; font-size: 14px;">Price</th>
                                    <th style="padding: 12px; color: #475569; font-size: 14px;">Total</th>
                                    <th style="padding: 12px; color: #16a34a; font-size: 14px;">Your Earning</th>
                                </tr>
                            </thead>
                            <tbody>
                                ${productsHtml}
                            </tbody>
                            ${productList.length > 0 ? `
                            <tfoot>
                                <tr style="background-color: #f8fafc; border-top: 2px solid #e2e8f0;">
                                    <td colspan="3" style="padding: 15px 12px; text-align: right; color: #333; font-weight: bold;">Total Expected Earning:</td>
                                    <td style="padding: 15px 12px; color: #16a34a; font-weight: bold; font-size: 16px;">${formatLKR(totalEarning)}</td>
                                </tr>
                            </tfoot>
                            ` : ''}
                        </table>

                        <div style="background-color: #fffbeb; border: 1px solid #fde68a; padding: 15px; border-radius: 8px; margin-top: 25px;">
                            <p style="margin: 0; color: #b45309; font-size: 14px;">
                                <strong>Next Action:</strong> Please log in to your Vendor Hub to explicitly mark this order as "Processing" once you begin preparing the package.
                            </p>
                        </div>
                    </div>
                    
                    <div style="background-color: #f1f5f9; padding: 20px; text-align: center; border-top: 1px solid #e2e8f0;">
                        <a href="https://shopx.lk/seller/login" style="background-color: #2563eb; color: white; padding: 10px 20px; text-decoration: none; border-radius: 6px; font-weight: bold; display: inline-block;">Go to Vendor Hub</a>
                        <p style="color: #94a3b8; font-size: 12px; margin-top: 15px; margin-bottom: 0;">This is an automated notification from ShopX Marketplace.</p>
                    </div>
                </div>
            `;
        } else {
            return NextResponse.json({ success: false, message: "Invalid email type requested." }, { status: 400 });
        }

        // Send Email via Resend targeting the company inbox
        const { data: resendData, error } = await resend.emails.send({
            from: "ShopX Automated <onboarding@resend.dev>", // Requires verified domain in prod, using testing domain
            to: ["info.shopx.lk@gmail.com"],
            subject: subject,
            html: htmlTemplate,
        });

        if (error) {
            console.error("Resend API Error:", error);
            return NextResponse.json({ success: false, message: error.message }, { status: 500 });
        }

        return NextResponse.json({ success: true, data: resendData });

    } catch (err: any) {
        console.error("Email API Handler Error:", err);
        return NextResponse.json({ success: false, message: err?.message || "Internal server error" }, { status: 500 });
    }
}
